name: nest_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  supabase_flutter: ^2.9.1
  fl_chart: ^0.68.0
  provider: ^6.0.5
  image_picker: ^1.0.7
  shared_preferences: ^2.2.3
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2

  # âœ… i18n / l10n
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/logo.png
